services:
  database:
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  cache:
    image: memcached:alpine
    command:
      - --memory-limit=128
    ports:
      - 11211:11211
