services:
  database:
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  cache:
    image: memcached:alpine
    command:
      - --memory-limit=128
    ports:
      - 11211:11211
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.rabbitmq:/var/lib/rabbitmq
